#ifndef EVENTS_H_
#define EVENTS_H_

typedef enum
{	
	/*Ignition*/
	IGNITION_OFF_EVENT,
	IGNITION_ACC_EVENT,
	IGNITION_ON_EVENT,
	IGNITION_START_EVENT,
	
	/*Door*/
	DOOR_OPEN_EVENT,
	DOOR_CLOSE_EVENT,
	LOCK_REQUEST_EVENT,
	UNLOCK_REQUEST_EVENT,
	
	/*Vehicle movement*/
	VEHICLE_STOPPED_EVENT,
	VEHICLE_MOVING_EVENT,
	
	/*Blinkers*/
	LEFT_BLINKER_REQUEST,
	RIGHT_BLINKER_REQUEST,
	HAZARD_REQUEST,
	
	/*Wipers*/
	WIPER_OFF_REQUEST,
	WIPER_INT_REQUEST,
	WIPER_LOW_REQUEST,
	WIPER_HIGH_REQUEST,
	
	/*Diagnostic*/
	TECHNICIAN_DIAG_REQUEST,
	DIAG_TIMEOUT_EVENT,
	ECU_RESET_EVENT,	
	
	/*Fault*/
	FAULT_CRITICAL_EVENT,
	FAULT_CLEARED_EVENT	
}ecu_event_t;

#endif /* EVENTS_H_ */